### ISSUE TITLE
Slack invite Desenvolvedor Front End

### ISSUE THREAD

**Issue by beatrizyumi** [udacity/br-fend-issues#1]
Os links para invite do slack nacional do curso de nanodegree de Desenvolvedor Front End apenas redirecionam para a página de login.

**Comment by rblima0** [comment]
Também estou com o mesmo problema !

**Comment by thalescomp** [comment]
Oi, pessoal! Vocês estão conseguindo agora? Tinha resolvido esse problema um tempo atrás, mas acabei esquecendo de atualizar aqui. :+1:
